import { Inter } from "next/font/google";
import "./globals.css";
import SideBar from "@/components/SideBar";
import Details from "@/components/Details";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Thirdi",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="flex w-full relative max-h-screen min-h-screen">
        <SideBar />
        <div className="w-full border-x border-grey-600 custom-scrollbar overflow-y-scroll">{children}</div>
        <Details />
      </body>
    </html>
  );
}
