import { Inter } from "next/font/google";
import "./globals.css";
import SideBar from "@/components/SideBar";
import Header from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Thirdi",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className=" grid grid-cols-6 w-full relative min-h-screen">
        <SideBar/>
      <div className="content col-start-2 col-span-5 w-full relative">
        <Header />
        {children}
        </div>
        </body>
    </html>
  );
}
